### ISSUE TITLE
Improve developer's tooling

### ISSUE THREAD

**Issue by repli2dev** [Crell/Serde#20]
## Detailed description

Provide configured PHPStan and PHPCS (or Easy Coding Standard) to easily run the desired checks so the code reviews may be less of style checks.

## Context

- PHPStan installed but not configured in `composer.json`, it also not configured by default.
- PHPCS is configured in `composer.json` but the code standard is not changed to support the code base (returns too many errors)

## Possible implementation

TBA

## Your environment

- Default repository checkout

**Comment by Crell** [comment]
You're talking about just wiring up the existing checks to GitHub Actions, right?  (I've only just started messing with GHA in any detail at work, which is why I didn't do so originally.)
