### ISSUE TITLE
Support for default class settings without explicitly adding attributes

### ISSUE THREAD

**Issue by jameslkingsley** [Crell/Serde#55]
## Detailed description

This is a question / suggestion as I'm not sure whether it can be done with the current tools available, but it doesn't seem like it can. Essentially I want a way to define default `ClassSettings` that apply to _all_ classes whether they have the `ClassSettings` attribute defined or not.

The way it'd work is you specify a config somewhere, maybe just static properties on a class, and then when the analyzer reads your class it uses that config as the default values. Then if a class has its own `ClassSettings` attribute it can just override the default config.

## Context

Currently I have to add `ClassSettings` to every class I intend on using with Serde in order to `renameWith: Case::snake_case`. This becomes quite tedious and isn't DRY.

## Possible implementation

Simplest support for this would probably be to break up the `Analyzer` a bit so that it's easier to extend with a custom analyzer. In order to support what I'm proposing I'd have to copy a lot of code in `Analyzer::analyze` to hook into the place where it needs to be. If instead I could just add an interface to my extension of `SerdeCommon` that provides the default `ClassSettings` instance to use in the analyzer, then I think that'd solve it without many code changes.

## Your environment

N/A

**Comment by Crell** [comment]
I wouldn't want to do this in AttributeUtils, I think.  The "defaults" that AttributeUtils uses are what's defined in the attribute class; I think it's unwise to change that.

It might be possible to do in Serde, but it would likely require cloning the classDef with new values based on some defaults provided to Serde somehow.  Given that there's multiple places the classDef is looked up, that could be a challenge.

As a partial workaround, you can easily sub-class `ClassSettings` yourself and use that.  Something like (I didn't test or lint this, just writing it out as an example):

```php
#[\Attribute]
class MyDefaults extends ClassSettings {
      public function __construct(
        bool $includeFieldsByDefault = true,
        array $scopes = [null],
        bool $requireValues = false,
        ?RenamingStrategy $renameWith = null,
    ) {
        parent::__construct($includeFieldsByDefault, $scopes, $requireValues, $renameWith ?? Case::snake_case);
    }
}

#[MyDefaults]
class SerializeMe { ... }
```

I'm pretty sure that would work.  You'd still have to tag every class, but at least you can centralize your defaults and any other overrides you want so it's easier to manage later.

(That same trick should work for Field as well, if you're so inclined.)

**Comment by jameslkingsley** [comment]
Thanks, yeah a custom attribute class is what I'm using for now, which does make things easier. I appreciate the complexity in adding something like this 👍🏻
