### ISSUE TITLE
Possibility to exclude `null` values from serialization?

### ISSUE THREAD

**Issue by shanginn** [Crell/Serde#60]
## Detailed description

Is there a way to skip null values from serialization, for example like in [Symfony serizalizer](https://symfony.com/doc/current/components/serializer.html#skipping-null-values)?

## Context

I have a generic object for an API request with optional fields. And if the field if filled it should be for example an array.

The api server expects array too and do not accept null value in that field and throws a 400 bad request.

I think this is a common use case to omit unused null values before request and maybe there is a way to do it with this library and I just could not find how?

**Comment by Crell** [comment]
I'm not entirely sure I follow.  You have this:

```php
class Foo {
  public string $name = 'Hello';
  public ?array $bar = null;
}
```

And want it serialized to:

```json
{
  "name": "Hello"
}
```

or to

```json
{
  "name": "Hello",
  "bar": []
}

```

I'm not sure what you intend here.

**Comment by shanginn** [comment]
sorry for no example. the first option.
from 
```php
class Foo {
  public string $name = 'Hello';
  public ?array $bar = null;
}
```

to 

```json
{
  "name": "Hello"
}
```

**Comment by shanginn** [comment]
I feel you brother, but if you can suggest any other way (like Option) to get it done like this I'm all ears :)

How about `Field.exclude` accepting not only a bool, but also possible a callback that returns bool with the object itself as an argument?

something like this
```php
class Foo {
  public string $name = 'Hello';
  #[Field(exclude: fn (Foo $foo): bool => $foo === null)]
  public ?array $bar = null;
}
```

It nice to also have class-wide null-skipping option, but this callback option might be useful for other things too

**Comment by Crell** [comment]
Fixed in `master`.  Not sure when I'll tag a new release.  There's a few other outstanding requests I want to get to first, and some test cleanup.

**Comment by shanginn** [comment]
thanks!
