### ISSUE TITLE
Can't deserialize nullable Enum

### ISSUE THREAD

**Issue by nuvalis** [Crell/Serde#66]
In EnumExport there is no handling of a nullable Enum which will cause the string backed Enum::from() to throw an exception
https://github.com/Crell/Serde/blob/a3229d7a4c98861b186abf06802f6740d4b7d9cd/src/PropertyHandler/EnumExporter.php#L35

Example
```
class MyClassDTO {
    private ?ServiceTypeEnum $internalServiceType = null;
}

$data = [
    'internalServiceType' => null
];

$serde = new SerdeCommon();
$serde->deserialize($data, from: 'array', to: MyClassDTO::class);
```

```
TypeError : App\Services\Delivery\ServiceTypeEnum::from(): Argument #1 ($value) must be of type string, null given
vendor/crell/serde/src/PropertyHandler/EnumExporter.php:54
```

I tried adding this after the match case, which solved my issue
```
// src/PropertyHandler/EnumExporter.php

if ($field->nullable && $val === null) {
    return $val;
}
```

**Comment by Crell** [comment]
You are correct, good catch.  Fixed now.
