### ISSUE TITLE
SequenceField not working with Doctrine Collections although it is a Traversable

### ISSUE THREAD

**Issue by dgoosens** [Crell/Serde#75]
AFAIK, it should be possible to use the `SequenceField` attribute on any `Traversable`, such as a Doctrine ArrayCollection.  
This appears not to be the case as the `validate` method uses the `array_is_list` method that only accepts `array`s and not any kind of `Traversable`

Example:

```php
<?php

class FooWithArrayCollection
{
    public function __construct(
        /**
         * @var ArrayCollection<int, \DateTimeImmutable>
         */
        #[SequenceField(arrayType: \DateTimeImmutable::class)]
        public ArrayCollection $collection
    )
    {
    }
}
```

```php
<?php
     $foo = new FooWithArrayCollection(new ArrayCollection([new \DateTimeImmutable()]));
     $serde = new SerdeCommon();
     $json = $serde->serialize($foo, 'json');

     $obj = $serde->deserialize($json, 'json', FooWithArrayCollection::class);
````

The `deserialize` will throw 

```
TypeError : array_is_list(): Argument #1 ($array) must be of type array, Doctrine\Common\Collections\ArrayCollection given
```

This Exception is thrown by `SequenceField::validate`

FWIW, if I try to correct this `validate` method and have it return `true` (see example above), I'm getting another Exception thrown:

```
Undefined property: Crell\Serde\Attributes\SequenceField::$keyType 
```

So I might be missing something...

**Comment by dgoosens** [comment]
When using `ClassNameTypeMap`, it does deal with the ArrayCollection as expected:

```php
<?php
class FooWithArrayCollection
{
    public function __construct(
        #[ClassNameTypeMap(key: 'type')]
        public ArrayCollection $collection,
    )
    {
    }
}
```

meaning, that when deserializing the serialized object, it does create a correct `ArrayCollection`, but I can not figure out a way to type the elements in the Collection

**Comment by Crell** [comment]
From the README:

> If a property is typed to be some other Traversable object (usually because it implements either \Iterator or \IteratorAggregate), then it will be serialized and deserialized as a normal object. Its iterable-ness is ignored. In this case, the #[SequenceField] and #[DictionaryField] attributes are forbidden.

cf: https://github.com/Crell/Serde?tab=readme-ov-file#generators-iterables-and-traversables

So Serde not treating a doctrine collection as an array-ish is expected behavior.

Adding a way to make it do so would be a feature request.  Off hand I'm not 100% sure how to best do that.

**Comment by dgoosens** [comment]
looks like it is very trivial to deal with this with a custom `Importer` and `Exporter`

```php
<?php
declare(strict_types=1);

namespace App\Infrastructure\Serde\PropertyHandler;

use Crell\Serde\Attributes\Field;
use Crell\Serde\CollectionItem;
use Crell\Serde\Deserializer;
use Crell\Serde\PropertyHandler\Exporter;
use Crell\Serde\PropertyHandler\Importer;
use Crell\Serde\Sequence;
use Crell\Serde\Serializer;
use Doctrine\Common\Collections\Collection;

class DoctrineCollectionExporter implements Importer, Exporter
{
    public function exportValue(Serializer $serializer, Field $field, mixed $value, mixed $runningValue): mixed
    {
        $seq =  $this->iterableToSequence($value);
        return $serializer->formatter->serializeSequence($runningValue, $field, $seq, $serializer);
    }

    /**
     * @param mixed[] $value
     */
    protected function iterableToSequence(iterable $value): Sequence
    {
        $seq = new Sequence();

        $seq->items = (static function () use ($value) {
            foreach ($value as $k => $v) {
                $f = Field::create(serializedName: "$k", phpType: \get_debug_type($v));
                yield new CollectionItem(field: $f, value: $v);
            }
        })();
        return $seq;
    }

    public function canExport(Field $field, mixed $value, string $format): bool
    {
        return $value instanceof Collection;
    }

    public function importValue(Deserializer $deserializer, Field $field, mixed $source): mixed
    {
        $data = $deserializer->deformatter->deserializeSequence($source, $field, $deserializer);
        return new ($field->phpType)($data);
    }

    public function canImport(Field $field, string $format): bool
    {
        return \is_a($field->phpType, Collection::class, true); ;
    }
}
```

and injecting the handler into `SerdeCommon`

```php
<?php
    $foo = new FooWithArrayCollection(new ArrayCollection([new \DateTimeImmutable()]));
        
    $serde = new SerdeCommon(handlers: [
        new DoctrineCollectionExporter()
    ]);
        
    $json = $serde->serialize($foo, 'json');
    $obj = $serde->deserialize($json, 'json', FooWithArrayCollection::class);
```


**NOTES**

the `iterableToSequence` method above comes from `Crell\Serde\PropertyHandler\SequenceExporter` and so does the `$data = $deserializer->deformatter->deserializeSequence($source, $field, $deserializer);` conversion for the import

**Comment by Crell** [comment]
I knew making Importers/Exporters and TypeFields so flexible was the right thing to do. :smile:

**Comment by dgoosens** [comment]
Yes... it is quite flexible like this

I did notice though that it is not possible to overload one of the handlers that are predefined 

Might be handy, IMHO, if that were possible, don't you think?

For instance, currently working on a DateTime conversion issue... and would be much easier to inject a custom handler that would overload the existing one

**Comment by Crell** [comment]
A custom handler should be triggered before the built in ones, I think?  

Ah, wait, no, it's not: https://github.com/Crell/Serde/blob/master/src/SerdeCommon.php#L77

Probably the easiest thing to do is have your own class that extends `Serde` and sets up exactly the handlers you want, in exactly the order you want.  That's why it's separate from `SerdeCommon`, exactly so people can do that.
