### ISSUE TITLE
Datetime conversion and microseconds

### ISSUE THREAD

**Issue by dgoosens** [Crell/Serde#76]
hi @Crell 

Wondering if it would not be appropriate to replace the default DateTime format `Y-m-d\TH:i:s.vP`  (`RFC3339_EXTENDED`) by `'Y-m-d\TH:i:s.uP` ? 
(See, a `u` instead of a `v`)

Currently, serialization of a DateTime object will strip the microseconds... and when deserializing, before and after values won't match anymore

example:

```php
<?php

        $serde = new SerdeCommon();
        $dt = new \DateTimeImmutable();
        \var_export($dt);
        // DateTimeImmutable::__set_state(array(
        //   'date' => '2024-12-09 14:11:03.654257',
        //   'timezone_type' => 3,
        //   'timezone' => 'Europe/London',
        //))

        $serialized = $serde->serialize($dt, 'json');
        \var_export($serialized);
        // "2024-12-09T14:11:03.654+00:00"`
       // >> see the microseconds are gone

        $deserialized = $serde->deserialize($serialized, 'json', \DateTimeImmutable::class);
        var_export($deserialized);
        // DateTimeImmutable::__set_state(array(
        //   'date' => '2024-12-09 14:11:03.654000',
        //   'timezone_type' => 1,
        //   'timezone' => '+00:00',
        //))
```

also notice that the `timezone_type` and `timezone` get out of sync (even though, they are technically the same)

**Comment by heiglandreas** [comment]
> (even though, they are technically the same)

Nitpicking: They are not. `Europe/London` contains information about DST and rough geographical location whereas `+01:00` is just a fancy way of saying "I converted it to UTC" without any other information. 😉 

For a serialization lib where I expect things to get out exactly the way they go in that looks like a severe issue....

**Comment by dgoosens** [comment]
> > (even though, they are technically the same)
> 
> Nitpicking: They are not. `Europe/London` contains information about DST and rough geographical location whereas `+01:00` is just a fancy way of saying "I converted it to UTC" without any other information. 😉
> 
> For a serialization lib where I expect things to get out exactly the way they go in that looks like a severe issue....

thanks for participating @heiglandreas 

right...  
so, maybe a PR for `DateTimeExporter` might be in order then

**Comment by heiglandreas** [comment]
> so, maybe a PR for DateTimeExporter might be in order then

Yeah... Looks like @crell has already coverded the cases. When no timezone is specified the set one will be used and when one specifies a timezone to convert to, then that one will be used. That is a conscious deccission of a developer that one has to use. I doubt that in 99% of the cases that developer knows what they are doing there, but that is a totally different topic! The lib does what it is supposed to do. Solving layer 8-10 problems is not in scope though...

**Comment by dgoosens** [comment]
> > so, maybe a PR for DateTimeExporter might be in order then
> 
> Yeah... Looks like @Crell has already covered the cases. When no timezone is specified the set one will be used and when one specifies a timezone to convert to, then that one will be used.
> 
> That is a conscious decision of a developer that one has to accept.
> 
> I doubt that in 99% of the cases that developer knows what they are doing there, but that is a totally different topic! The lib does what it is supposed to do. Solving layer 8-10 problems is not in scope though...

yes... but the timezone information is lost during the conversion...  
this is not an issue when communicating with a JS front   
but I could see issues when using in NoSQL context or with server-to-server communication

**Comment by Crell** [comment]
Isomorphic serialization/deserialization is the goal, but not always possible for a variety of reasons.  (Invalid data, certain formats that don't support certain features like `null`, etc.)

In this case, I'm not sure what the ask is, exactly.  You can very easily set a format for a DateField to one that includes microseconds if needed.  But that's quite rarely needed, and "the format used by JS/JSON" is the current default, which I still believe is the correct default.  (Changing the default would likely be a BC change anyway.)

**Comment by heiglandreas** [comment]
I'd close this. When converting to JSON without any further information the default rules need to be applied. And sadly PHP is one of the languages with decent datetime support. JavaScript on the other hand isn't. And JSON is still mainly based on JS capabilities. So converting to something that not everywhere  has the ability to handle nanoseconds or timezones (offsets aren't timezones!) necessarily looses information. If you want to avoid that you will need to explicitly set a conversion for the datetimes. Which will make the datetime in your JSON less universally understandable.

**Comment by dgoosens** [comment]
thanks @Crell & @heiglandreas  
closing this indeed as it is not the responsibility of Serde to deal with the limitations of JS
